name: Build and test React app

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
